# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVFWFGwdQdX7xA41uG-Et1HdUurKp4yo
"""

!pip install pyttsx3
!pip install gTTS

from gtts import gTTS
from IPython.display import Audio

# Load CSV file
with open('quotes.csv') as csvfile:
    quotes = list(csv.DictReader(csvfile))

# Define functions
def get_quote():
    # Select random quote
    quote = random.choice(quotes)
    
    # Convert quote to speech
    engine = gTTS(quote['Quote'])
    engine.save('quote.mp3')
    
    # Return quote and author
    return quote['Quote'], quote['Author']

# Get and play quote
quote, author = get_quote()
print(quote)
Audio('quote.mp3', autoplay=True)

